name: Keep Render Awake

on:
  schedule:
    - cron: '*/1 * * * *'   # toutes les minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping twice per minute
        run: |
          # Premier ping à T+0s
          curl -fsS https://backend-tutoci.onrender.com/healthcheck || true
          # Attendre 40 secondes
          sleep 40
          # Deuxième ping à T+40s
          curl -fsS https://backend-tutoci.onrender.com/healthcheck || true
